---
version: "3.8"

services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - ./env/settings.env
      - ./env/secrets.env
    image: bitwarden/self-host:beta
    restart: always
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden

  db:
    env_file:
      - ./env/settings.env
      - ./env/secrets.env
    image: mariadb:10
    restart: always
    volumes:
      - data:/var/lib/mysql

  nginx:
    depends_on:
      - bitwarden
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.crt:/etc/nginx/certs/cert.crt
      - ./ssl/cert.key:/etc/nginx/certs/cert.key
    ports:
      - 80:80
      - 443:443

volumes:
  bitwarden:
  logs:
  data: