---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc-etc
  namespace: bitwarden
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc-logs
  namespace: bitwarden
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc-data
  namespace: bitwarden
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
